### ISSUE TITLE
About your problem

### ISSUE THREAD

**Issue by dragonHyeon** [MingtaoGuo/SinGAN_Pytorch#2]
Hello.
First of all, thanks for your code! I refered your code and reimplemented SinGAN again.

The image which were occuring problem you described when training with your code doesn't occur any problem with my code. The difference between yours and mine are

- the method of normalization (or standardization). I've calculated std and mean for each image. Since we are training the model using only one single image I think it's dangerous to use common std and mean. To be more precise I've also calculated std and mean for each individual scale.
- z_rec issue which I mentioned in my PR #1 

If you want to get some idea, you can take a look at my code on my repo https://github.com/dragonHyeon/pytorch-basic-model-implementation/tree/master/SinGAN.
I wish you could solve your problem.

Good luck!
![huashan_results](https://github.com/MingtaoGuo/SinGAN_Pytorch/assets/30744922/4b0fd4b1-32f1-4e59-8613-0cd63ea188b0)

**Comment by dragonWorker** [comment]
Hey, I figured out the problem!
I also faced same problem with you and the reason why this happend was due to **pixel values that exceeded the proper range**.

When I visualized the generated image using matplotlib it was clipping pixel values automatically, showing following message, which results in this clean image. https://github.com/MingtaoGuo/SinGAN_Pytorch/issues/2#issue-1758740914

> Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).

However when I tried to visualize the generated image using PIL image, which doesn't fix pixel values automatically, I got these results just as similar as yours.

![huashan_error](https://github.com/MingtaoGuo/SinGAN_Pytorch/assets/90813253/d09391fe-106a-493b-8d63-4daedcc9fd40)

My solution was to regulate those data range manually by myself using code something like this.

`fake_x[fake_x > 1] = 1`

`fake_x[fake_x < 0] = 0`

Fianlly, I could get this clean image.

![huashan_correct](https://github.com/MingtaoGuo/SinGAN_Pytorch/assets/90813253/c75f2cfd-f526-4633-be97-cec483fdca5d)

Best solution might be to ensure the model to output the image which all values are between 0 and 1. I should study more for this.

**Comment by dragonHyeon** [comment]
Hey, I figured out the problem!
I also faced same problem with you and the reason why this happend was due to **pixel values that exceeded the proper range**.

When I visualized the generated image using matplotlib it was clipping pixel values automatically, showing following message, which results in this clean image. https://github.com/MingtaoGuo/SinGAN_Pytorch/issues/2#issue-1758740914

> Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).

However when I tried to visualize the generated image using PIL image, which doesn't fix pixel values automatically, I got these results just as similar as yours.

![huashan_error](https://github.com/MingtaoGuo/SinGAN_Pytorch/assets/90813253/d09391fe-106a-493b-8d63-4daedcc9fd40)

My solution was to regulate those data range manually by myself using code something like this.

`fake_x[fake_x > 1] = 1`

`fake_x[fake_x < 0] = 0`

Fianlly, I could get this clean image.

![huashan_correct](https://github.com/MingtaoGuo/SinGAN_Pytorch/assets/90813253/c75f2cfd-f526-4633-be97-cec483fdca5d)

Best solution might be to ensure the model to output the image which all values are between 0 and 1. I should study more for this.

**Comment by dragonHyeon** [comment]
Hey, I figured out the problem!
I also faced same problem with you and the reason why this happend was due to **pixel values that exceeded the proper range**.

When I visualized the generated image using matplotlib it was clipping pixel values automatically, showing following message, which results in this clean image. https://github.com/MingtaoGuo/SinGAN_Pytorch/issues/2#issue-1758740914

> Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).

However when I tried to visualize the generated image using PIL image, which doesn't fix pixel values automatically, I got these results just as similar as yours.

![huashan_error](https://github.com/MingtaoGuo/SinGAN_Pytorch/assets/90813253/d09391fe-106a-493b-8d63-4daedcc9fd40)

My solution was to regulate those data range manually by myself using code something like this.

`fake_x[fake_x > 1] = 1`

`fake_x[fake_x < 0] = 0`

Fianlly, I could get this clean image.

![huashan_correct](https://github.com/MingtaoGuo/SinGAN_Pytorch/assets/90813253/c75f2cfd-f526-4633-be97-cec483fdca5d)

Best solution might be to ensure the model to output the image which all values are between 0 and 1. I should study more for this.

**Comment by dragonHyeon** [comment]
Hey, I figured out the problem!
I also faced same problem with you and the reason why this happend was due to **pixel values that exceeded the proper range**.

When I visualized the generated image using matplotlib it was clipping pixel values automatically, showing following message, which results in this clean image. https://github.com/MingtaoGuo/SinGAN_Pytorch/issues/2#issue-1758740914

> Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).

However when I tried to visualize the generated image using PIL image, which doesn't fix pixel values automatically, I got these results just as similar as yours.

![huashan_error](https://github.com/MingtaoGuo/SinGAN_Pytorch/assets/90813253/d09391fe-106a-493b-8d63-4daedcc9fd40)

My solution was to regulate those data range manually by myself using code something like this.

`fake_x[fake_x > 1] = 1`

`fake_x[fake_x < 0] = 0`

Fianlly, I could get this clean image.

![huashan_correct](https://github.com/MingtaoGuo/SinGAN_Pytorch/assets/90813253/c75f2cfd-f526-4633-be97-cec483fdca5d)

Best solution might be to ensure the model to output the image which all values are between 0 and 1. I should study more for this.

**Comment by dragonHyeon** [comment]
Hey, I figured out the problem!
I also faced same problem with you and the reason why this happend was due to **pixel values that exceeded the proper range**.

When I visualized the generated image using matplotlib it was clipping pixel values automatically, showing following message, which results in this clean image. https://github.com/MingtaoGuo/SinGAN_Pytorch/issues/2#issue-1758740914

> Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).

However when I tried to visualize the generated image using PIL image, which doesn't fix pixel values automatically, I got these results just as similar as yours.

![huashan_error](https://github.com/MingtaoGuo/SinGAN_Pytorch/assets/90813253/d09391fe-106a-493b-8d63-4daedcc9fd40)

My solution was to regulate those data range manually by myself using code something like this.

`fake_x[fake_x > 1] = 1`

`fake_x[fake_x < 0] = 0`

Finally, I could get this clean image.

![huashan_correct](https://github.com/MingtaoGuo/SinGAN_Pytorch/assets/90813253/c75f2cfd-f526-4633-be97-cec483fdca5d)

Best solution might be to ensure the model to output the image range between 0 and 1.

**Comment by MingtaoGuo** [comment]
> Hey, I figured out the problem! I also faced same problem with you and the reason why this happend was due to **pixel values that exceeded the proper range**.
> 
> When I visualized the generated image using matplotlib it was clipping pixel values automatically, showing following message, which results in this clean image. [#2 (comment)](https://github.com/MingtaoGuo/SinGAN_Pytorch/issues/2#issue-1758740914)
> 
> > Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
> 
> However when I tried to visualize the generated image using PIL image, which doesn't fix pixel values automatically, I got these results just as similar as yours.
> 
> ![huashan_error](https://user-images.githubusercontent.com/90813253/246846667-d09391fe-106a-493b-8d63-4daedcc9fd40.png)
> 
> My solution was to regulate those data range manually by myself using code something like this.
> 
> `fake_x[fake_x > 1] = 1`
> 
> `fake_x[fake_x < 0] = 0`
> 
> Finally, I could get this clean image.
> 
> ![huashan_correct](https://user-images.githubusercontent.com/90813253/246848742-c75f2cfd-f526-4633-be97-cec483fdca5d.png)
> 
> Best solution might be to ensure the model to output the image range between 0 and 1.

Great! ! Thank you for helping me solve the problem that has been bothering me for many years.
